name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Se ejecuta todos los días a medianoche (UTC)
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v2
        id: snake-gif
        with:
          github_user_name: EmanuelRobinson
          outputs: |
            dist/github-contribution-grid-snake.svg
      - uses: actions/upload-artifact@v3
        with:
          name: snake-gif
          path: dist/github-contribution-grid-snake.svg
      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

